version: '3'
services:

  api:
    build: ./api
    networks:
      - frontend
    environment:
      PORT: 3000

  client:
    build: ./client
    ports:
      - 80:80
    networks:
      - frontend

networks:
  frontend: